/*
 * ============================================================
 * JAVA EVENT HANDLING
 * ============================================================
 *
 * Event handling is the mechanism that controls the event and
 * decides what should happen if an event occurs.
 *
 * ============================================================
 * EVENT CLASSES (java.awt.event):
 * ============================================================
 *
 * 1. ActionEvent
 *    - Generated when button is clicked, menu item selected,
 *      or Enter pressed in text field
 *    - Methods: getActionCommand(), getSource()
 *
 * 2. MouseEvent
 *    - Generated by mouse actions (click, press, release, etc.)
 *    - Methods: getX(), getY(), getClickCount(), getButton()
 *    - Mouse buttons: BUTTON1 (left), BUTTON2 (middle), BUTTON3 (right)
 *
 * 3. KeyEvent
 *    - Generated when key is pressed, released, or typed
 *    - Methods: getKeyCode(), getKeyChar(), isShiftDown(), isCtrlDown()
 *    - Key codes: VK_ENTER, VK_ESCAPE, VK_A, VK_1, etc.
 *
 * 4. WindowEvent
 *    - Generated for window state changes (open, close, minimize)
 *
 * 5. FocusEvent
 *    - Generated when component gains or loses focus
 *
 * ============================================================
 * LISTENER INTERFACES:
 * ============================================================
 *
 * 1. ActionListener
 *    - Methods: actionPerformed(ActionEvent e)
 *
 * 2. MouseListener
 *    - Methods:
 *      - mouseClicked(MouseEvent e)  - click (press + release)
 *      - mousePressed(MouseEvent e)  - mouse button pressed
 *      - mouseReleased(MouseEvent e) - mouse button released
 *      - mouseEntered(MouseEvent e)  - mouse enters component
 *      - mouseExited(MouseEvent e)   - mouse exits component
 *
 * 3. MouseMotionListener
 *    - Methods:
 *      - mouseMoved(MouseEvent e)    - mouse moved
 *      - mouseDragged(MouseEvent e)  - mouse dragged
 *
 * 4. KeyListener
 *    - Methods:
 *      - keyPressed(KeyEvent e)  - key pressed down
 *      - keyReleased(KeyEvent e) - key released
 *      - keyTyped(KeyEvent e)    - key typed (press + release)
 *
 * 5. WindowListener
 *    - Methods: windowOpened, windowClosing, windowClosed, etc.
 *
 * ============================================================
 * ADAPTER CLASSES (Alternative to Listeners):
 * ============================================================
 * - MouseAdapter (implements MouseListener)
 * - KeyAdapter (implements KeyListener)
 * - WindowAdapter (implements WindowListener)
 * - Adapter classes provide empty implementations so you
 *   only need to override the methods you want to use
 *
 * ============================================================
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class BasicEventHandling {

    public static void main(String[] args) {
        JFrame f = new JFrame("Event Handling Example");

        // ==================== ACTION EVENT ====================
        JLabel nameLabel = new JLabel("Enter Name:");
        nameLabel.setBounds(20, 20, 100, 20);

        JTextField tf = new JTextField();
        tf.setBounds(120, 20, 150, 25);

        JButton b = new JButton("Click Me");
        b.setBounds(280, 20, 100, 25);

        JLabel actionResult = new JLabel("Action: ");
        actionResult.setBounds(20, 50, 380, 20);

        // ActionListener - triggered on button click
        b.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String name = tf.getText();
                actionResult.setText("Action: Welcome " + name + "!");
            }
        });

        // ==================== MOUSE EVENT ====================
        JPanel mousePanel = new JPanel();
        mousePanel.setBounds(20, 90, 360, 100);
        mousePanel.setBackground(Color.LIGHT_GRAY);
        mousePanel.setLayout(null);

        JLabel mousePanelLabel = new JLabel("Mouse Area - Click, Enter, Exit here");
        mousePanelLabel.setBounds(80, 10, 250, 20);
        mousePanel.add(mousePanelLabel);

        JLabel mouseResult = new JLabel("Mouse: Waiting for mouse event...");
        mouseResult.setBounds(20, 200, 380, 20);

        JLabel mousePosition = new JLabel("Position: X=0, Y=0");
        mousePosition.setBounds(20, 225, 380, 20);

        // MouseListener - handles mouse clicks and enter/exit
        mousePanel.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
                mouseResult.setText("Mouse: Clicked at (" + e.getX() + ", " + e.getY() + ")");
            }

            public void mousePressed(MouseEvent e) {
                mouseResult.setText("Mouse: Button Pressed - Button " + e.getButton());
            }

            public void mouseReleased(MouseEvent e) {
                mouseResult.setText("Mouse: Button Released");
            }

            public void mouseEntered(MouseEvent e) {
                mousePanel.setBackground(Color.CYAN);
                mouseResult.setText("Mouse: Entered the panel");
            }

            public void mouseExited(MouseEvent e) {
                mousePanel.setBackground(Color.LIGHT_GRAY);
                mouseResult.setText("Mouse: Exited the panel");
            }
        });

        // MouseMotionListener - handles mouse movement
        mousePanel.addMouseMotionListener(new MouseMotionListener() {
            public void mouseMoved(MouseEvent e) {
                mousePosition.setText("Position: X=" + e.getX() + ", Y=" + e.getY());
            }

            public void mouseDragged(MouseEvent e) {
                mousePosition.setText("Dragging: X=" + e.getX() + ", Y=" + e.getY());
            }
        });

        // ==================== KEY EVENT ====================
        JLabel keyLabel = new JLabel("Type here:");
        keyLabel.setBounds(20, 260, 80, 25);

        JTextField keyField = new JTextField();
        keyField.setBounds(100, 260, 200, 25);

        JLabel keyResult = new JLabel("Key: Waiting for key event...");
        keyResult.setBounds(20, 290, 380, 20);

        JLabel keyInfo = new JLabel("Key Info: ");
        keyInfo.setBounds(20, 315, 380, 20);

        // KeyListener - handles keyboard events
        keyField.addKeyListener(new KeyListener() {
            public void keyPressed(KeyEvent e) {
                int keyCode = e.getKeyCode();
                keyResult.setText("Key Pressed: " + KeyEvent.getKeyText(keyCode));
                keyInfo.setText("Key Code: " + keyCode + " | Char: " + e.getKeyChar());
            }

            public void keyReleased(KeyEvent e) {
                keyResult.setText("Key Released: " + KeyEvent.getKeyText(e.getKeyCode()));
            }

            public void keyTyped(KeyEvent e) {
                // keyTyped is called after keyPressed for character keys
            }
        });

        // Add all components to frame
        f.add(nameLabel);
        f.add(tf);
        f.add(b);
        f.add(actionResult);
        f.add(mousePanel);
        f.add(mouseResult);
        f.add(mousePosition);
        f.add(keyLabel);
        f.add(keyField);
        f.add(keyResult);
        f.add(keyInfo);

        f.setLayout(null);
        f.setSize(420, 400);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
    }
}
